from __future__ import annotations
from enum import Enum, auto
import itertools

_global_counter = itertools.count()

class ITTTypeChecking(Enum):
    @staticmethod
    def _generate_next_value_(name, start, count, last_values):
        return next(_global_counter)

class InternalTokenType(ITTTypeChecking):
    # ^ Miscellaneous
    
    EoF = auto() # End of File
    _IgnoreByTokenizer = auto()
    _SkipPattern = auto()

    Arrow = auto() # ->
    Identifier = auto()
    NewLine = auto()

    class Parentheses(ITTTypeChecking):
        OpenParenthesis = auto()
        CloseParenthesis = auto()
        OpenSquareBracket = auto()
        CloseSquareBracket = auto()
        OpenCurlyBrace = auto()
        CloseCurlyBrace = auto()
    
    class Keywords(ITTTypeChecking):
        Try = auto()
        Catch = auto()
        Finally = auto()
        From = auto()
        As = auto()
        Else = auto()
        While = auto()
        Not = auto()
        In = auto()
        NotIn = auto()
        Is = auto()
        IsNot = auto()
        Let = auto()
        Const = auto()
        Struct = auto()
        Enum = auto()
        If = auto()
        Elif = auto()
        Throw = auto()
        For = auto()
        Cfor = auto()
        Do = auto()
        Fn = auto()
        Class = auto()
        Import = auto()
        Raise = auto()
        Except = auto()
        Match = auto()
        Case = auto()
        Default = auto()
        Del = auto()
        End = auto()
        Func = auto()
        Fun = auto()
        Function = auto()
        Cls = auto()
        Elsif = auto()
        Elseif = auto()
        Def = auto()
        Switch = auto()
        Break = auto()
        Continue = auto()
        Scope = auto()
        Return = auto()
        Or = auto()
        And = auto()
        Xor = auto()
    
    class Symbols(ITTTypeChecking):
        Tilda = auto()
        Exclamation = auto()
        At = auto()
        Percent = auto()
        Caret = auto()
        DoubleCaret = auto()
        BAndCaret = auto()
        Andpersand = auto()
        DoubleAndpersand = auto()
        BAndAndpersand = auto()
        Asterisk = auto()
        DoubleAsterisk = auto()
        Plus = auto()
        DoublePlus = auto()
        Dash = auto()
        DoubleDash = auto()
        ForwardSlash = auto()
        DoubleForwardSlash = auto()
        BackSlash = auto()
        QuestionMark = auto()
        VerticalBar = auto()
        DoubleVerticalBar = auto()
        BAndVerticalBar = auto()
        Underscore = auto()
        Comma = auto()
        Dot = auto()
        Diamond = auto()
        InvertedDiamond = auto()
        SpaceCapsule = auto()
        QuirkyLookingFace = auto()
        ExclamationAndEqual = auto()
        DoubleDot = auto()
        TripleDot = auto()
        Colon = auto()
        DoubleColon = auto()
        Semicolon = auto()
        Equal = auto()
        DoubleEqual = auto()
        TripleEqual = auto()
        LessThan = auto()
        DoubleLessThan = auto()
        GreaterThan = auto()
        DoubleGreaterThan = auto()
        LessThanAndEqual = auto()
        GreaterThanAndEqual = auto()
        ColonAndEqual = auto()

        PlusAndEqual = auto()
        DashAndEqual = auto()
        AsteriskAndEqual = auto()
        ForwardSlashAndEqual = auto()
        DoubleForwardSlashAndEqual = auto()
        PercentAndEqual = auto()
        DoubleAsteriskAndEqual = auto()
        DoubleDotAndEqual = auto()
        AtAndEqual = auto()
        VerticalBarAndEqual = auto()
        AndpersandAndEqual = auto()
        CaretAndEqual = auto()
        BAndVerticalBarAndEqual = auto()
        BAndAndpersandAndEqual = auto()
        BAndCaretAndEqual = auto()

        EqualAndPlus = auto()
        EqualAndDash = auto()
        EqualAndAsterisk = auto()
        EqualAndForwardSlash = auto()
        EqualAndDoubleForwardSlash = auto()
        EqualAndPercent = auto()
        EqualAndDoubleAsterisk = auto()
        EqualAndDoubleDot = auto()
        EqualAndAt = auto()
        EqualAndVerticalBar = auto()
        EqualAndAndpersand = auto()
        EqualAndCaret = auto()
        EqualAndBAndVerticalBar = auto()
        EqualAndBAndAndpersand = auto()
        EqualAndBAndCaret = auto()

    class Primitives(ITTTypeChecking):
        Int = auto()
        Float = auto()
        String = auto()
        Boolean = auto()
        Null = auto()